### PR TITLE
Use SpikeUtil to get spike options

### PR DESCRIPTION
**Pull request by choonge**
For the most part, 0.10.1 appears to work well with spike-core 1.0. But compiling templates is resulting in templates which are not getting transformed (so the resulting .html for a post has exactly the same content as the original template). After some digging around, I found something that works for me and decided to send it as a PR.

Apologies for not adding tests, and for any other mistakes - I am very new to the world of (node)js.

---

Provides forward compatibility with spike-core 1.0. See also
https://gist.github.com/jescalan/8e39596765c66a192d00c2684437bf57#custom-plugin-updates .

Since spike-core 0.13.3 has the dependency `"spike-util": "^0.4.0"`, we should get 0.5.0-0 which introduces the `getSpikeOptions()` function. This should provide forward compatibility with spike-core 1.0.

### CODE REVIEW

**Comment by choonge** [comment]
Hmm.. I don't understand why the test is failing with `[Error: util.getSpikeOptions is not a function]` :/ Unfortunately Travis is not showing which version of spike-util it is installing, but from what I can see in package.json it should be 0.5.0-0.. @jescalan , can you tell what I should do to fix this?

**Comment by jescalan** [comment]
So you didn't add spike-util as a dependency, it's not in the package.json at all...

File: package.json [hunk 1]
```diff
@@ -13,6 +13,7 @@
     "reshape": "^0.4.0",
     "reshape-loader": "^0.4.0",
     "rooftop-client": "^0.2.1",
+    "spike-util": "^0.4.0",
```
Comment (jescalan) [inline package.json]: This is and old, pre-1.0 release. If you use the latest version it should help: https://github.com/static-dev/spike-util/releases

Comment (choonge) [inline package.json]: Hmm.. I had set it to ^0.4.0 since that version is also referenced by spike-core 0.13.3, which in turn is in spike-rooftop's dev-dependencies. But indeed - changing it to 1.0.0 seems to get me one step further. There's a new error now.

I'll try and set up my local project for testing, so I can fix it once and for all before committing and having Travis do the work :p  Thanks so far for your help.

Comment (jescalan) [inline package.json]: Yeah, so spike is on v1 now. You can run `yarn upgrade-interactive` to get all your dependencies up to date!

Comment (jescalan) [inline package.json]: This is probably a good example project to base changes off: https://github.com/static-dev/spike-datocms
